language: cpp
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - unzip
      - doxygen
script:
  - set -e
  - pushd ~
  - mkdir cmake
  - cd cmake
  - wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
  - chmod 766 cmake-3.8.0-Linux-x86_64.sh
  - sed -i -r "s/^interactive=TRUE$/interactive=FALSE/g" cmake-3.8.0-Linux-x86_64.sh
  - ./cmake-3.8.0-Linux-x86_64.sh
  - cd ~
  - wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
  - tar zxf boost_1_68_0.tar.gz
  - cd boost_1_68_0
  - ./bootstrap.sh
  - ./b2 install --toolset=gcc-8 --with-system --prefix=$HOME/boost
  - cd ~
  - wget https://github.com/catchorg/Catch2/archive/master.zip -O Catch2.zip
  - unzip Catch2.zip
  - cd Catch2-master
  - mkdir build
  - cd build
  - ~/cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_INSTALL_PREFIX=$HOME/Catch2 -DCATCH_BUILD_TESTING=Off -DBUILD_TESTING=Off -DCATCH_BUILD_EXAMPLES=Off -DCATCH_INSTALL_DOCS=Off
  - ~/cmake/bin/cmake --build . --target install
  - popd
  - mkdir build
  - cd build
  - ~/cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-8 -DBOOST_ROOT=$HOME/boost -DCMAKE_PREFIX_PATH="$HOME/Catch2;$HOME/rapidjson"
  - ~/cmake/bin/cmake --build .
  - ~/cmake/bin/ctest -VV
  - cd ..
  - rm -r -f build
  - rm -r -f ~/Catch2
  - mkdir build
  - cd build
  - ~/cmake/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-8 -DBOOST_ROOT=$HOME/boost -DCMAKE_INSTALL_PREFIX=$HOME/Quic -DCMAKE_PREFIX_PATH=$HOME/rapidjson
  - ~/cmake/bin/cmake --build . --target install
  - cd ..
  - rm -r -f build
  - mkdir build
  - cd build
  - ~/cmake/bin/cmake ../travis/install_test -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-8 -DBOOST_ROOT=$HOME/boost -DCMAKE_PREFIX_PATH="$HOME/Quic;$HOME/rapidjson"
  - ~/cmake/bin/cmake --build .
  - ./bin/exec
