if(NOT TARGET Sockets::Sockets)
  add_library(Sockets::Sockets INTERFACE IMPORTED)
  if (${CMAKE_SYSTEM} MATCHES "Windows")
    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
      set_target_properties(Sockets::Sockets PROPERTIES INTERFACE_LINK_LIBRARIES ws2_32)
    else()
      set_target_properties(Sockets::Sockets PROPERTIES INTERFACE_LINK_LIBRARIES wsock32 ws2_32)
    endif()
  elseif(${CMAKE_SYSTEM} MATCHES "INtime")
    set_target_properties(Sockets::Sockets PROPERTIES INTERFACE_LINK_LIBRARIES netlib)
  endif()
endif()
